version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.6.10-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=airflow
      - RABBITMQ_DEFAULT_PASS=airflow
      - RABBITMQ_DEFAULT_VHOST=airflow

  mysql:
    image: mysql:5.7.18
    environment:
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
      - MYSQL_DATABASE=airflow
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ONETIME_PASSWORD=yes

  webserver:
    build: .
    restart: always
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
    volumes:
      - ~/docker-airflow/dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  flower:
    build: .
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - EXECUTOR=Celery
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    build: .
    restart: always
    depends_on:
      - webserver
    volumes:
      - ~/docker-airflow/dags:/usr/local/airflow/dags
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
    command: scheduler

  worker:
    build: .
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ~/docker-airflow/dags:/usr/local/airflow/dags
    ports:
      - "8793:8793"
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
    command: worker
