version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.6.10-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=airflow
      - RABBITMQ_DEFAULT_PASS=airflow
      - RABBITMQ_DEFAULT_VHOST=airflow

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - LOAD_EX=y
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
    # volumes:
      # - ~/docker-airflow/dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  flower:
    build: .
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - EXECUTOR=Celery
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    build: .
    restart: always
    depends_on:
      - webserver
    # volumes:
      # - ~/docker-airflow/dags:/usr/local/airflow/dags
    environment:
      - LOAD_EX=y
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
    command: scheduler

  worker:
    build: .
    restart: always
    depends_on:
      - scheduler
    # volumes:
      # - ~/docker-airflow/dags:/usr/local/airflow/dags
    ports:
      - "8793:8793"
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
    command: worker
